name: Build and Test Signer Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./internal/signer/linux
      run: go build -v ./...

    - name: Test
      working-directory: ./internal/signer/linux
      run: go test -v ./...

    - name: Create Binaries
      run: ./build/scripts/linux_amd64.sh

    - uses: actions/upload-artifact@v3
      with:
        name: linux_amd64
        path: ./build/bin/linux_amd64/*
